/**
 * 내장 이벤트 템플릿 8종 (Step 8).
 *
 * 가뭄·홍수·풍년·흉년·전염병·식량 폭동(효과형) +
 * 대규모 이주(통지형) + 교역로 단절(효과형·루트 스코프).
 * 수치는 §33 평상시 밸런스 시나리오가 통과하도록 조율됐다.
 */
import type { EventTemplate } from "../types";

export const BUILTIN_TEMPLATES: EventTemplate[] = [
  {
    id: "drought",
    version: 1,
    category: "natural",
    kind: "effect",
    name: "가뭄",
    descriptionTemplate: "{settlement}에 장기 가뭄이 닥쳤다. 농지가 말라붙어 생산이 크게 줄었다.",
    scope: "settlement",
    preconditions: [],
    probability: {
      base: 0.0012,
      factors: [
        {
          source: "drought.summer",
          condition: { metric: "world.month", operator: "between", value: [4, 7] },
          multiplier: 1.6,
          explanation: "여름철 가뭄 위험 증가",
        },
      ],
    },
    duration: { minTicks: 12, maxTicks: 36 },
    immediateEffects: [],
    ongoingEffects: [
      { targetMetric: "settlement.foodProduction", operation: "multiply", value: 0.55, minimum: 0 },
    ],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 36,
    maximumConcurrentInstances: 1,
    importance: 80,
    tags: ["natural", "food"],
    source: "builtin",
  },
  {
    id: "flood",
    version: 1,
    category: "natural",
    kind: "effect",
    name: "홍수",
    descriptionTemplate: "{settlement}을 덮친 홍수가 비축 식량을 쓸어갔다.",
    scope: "settlement",
    preconditions: [{ metric: "settlement.areaRiverVolume", operator: "gt", value: 0 }],
    probability: {
      base: 0.0015,
      factors: [
        {
          source: "flood.wetseason",
          condition: { metric: "world.month", operator: "between", value: [2, 7] },
          multiplier: 1.8,
          explanation: "우기 홍수 위험 증가",
        },
      ],
    },
    duration: { minTicks: 4, maxTicks: 10 },
    immediateEffects: [
      { targetMetric: "settlement.foodStock", operation: "multiply", value: 0.7, minimum: 0 },
    ],
    ongoingEffects: [
      { targetMetric: "settlement.foodProduction", operation: "multiply", value: 0.85, minimum: 0 },
    ],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 18,
    maximumConcurrentInstances: 1,
    importance: 60,
    tags: ["natural", "food"],
    source: "builtin",
  },
  {
    id: "goodHarvest",
    version: 1,
    category: "natural",
    kind: "effect",
    name: "풍년",
    descriptionTemplate: "{settlement}에 풍년이 들었다. 곳간이 넘치고 시장이 활기를 되찾는다.",
    scope: "settlement",
    preconditions: [],
    probability: {
      base: 0.003,
      factors: [
        {
          source: "goodHarvest.autumn",
          condition: { metric: "world.month", operator: "between", value: [8, 10] },
          multiplier: 2.0,
          explanation: "수확철 풍년 가능성 증가",
        },
        {
          source: "goodHarvest.fertile",
          condition: { metric: "settlement.areaFertility", operator: "gte", value: 0.5 },
          multiplier: 1.4,
          explanation: "비옥한 토양의 결실 가능성",
        },
      ],
    },
    duration: { minTicks: 3, maxTicks: 6 },
    immediateEffects: [],
    ongoingEffects: [
      { targetMetric: "settlement.foodProduction", operation: "multiply", value: 1.35, minimum: 0 },
    ],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 12,
    maximumConcurrentInstances: 1,
    importance: 30,
    tags: ["natural", "food", "positive"],
    source: "builtin",
  },
  {
    id: "badHarvest",
    version: 1,
    category: "natural",
    kind: "effect",
    name: "흉년",
    descriptionTemplate: "{settlement}의 수확이 기대에 크게 못 미쳤다.",
    scope: "settlement",
    preconditions: [],
    probability: {
      base: 0.0025,
      factors: [],
    },
    duration: { minTicks: 6, maxTicks: 12 },
    immediateEffects: [],
    ongoingEffects: [
      { targetMetric: "settlement.foodProduction", operation: "multiply", value: 0.6, minimum: 0 },
    ],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 12,
    maximumConcurrentInstances: 1,
    importance: 50,
    tags: ["natural", "food"],
    source: "builtin",
  },
  {
    id: "epidemic",
    version: 1,
    category: "health",
    kind: "effect",
    name: "전염병",
    descriptionTemplate: "{settlement}에 전염병이 퍼지기 시작했다.",
    scope: "settlement",
    preconditions: [{ metric: "settlement.population", operator: "gte", value: 1500 }],
    probability: {
      base: 0.0008,
      factors: [
        {
          source: "epidemic.crowding",
          condition: { metric: "settlement.overcrowdingRatio", operator: "gte", value: 1 },
          multiplier: 2.0,
          explanation: "과밀 도시의 전염 위험 증가",
        },
        {
          source: "epidemic.existing",
          condition: { metric: "settlement.diseaseLevel", operator: "gte", value: 0.15 },
          multiplier: 2.0,
          explanation: "이미 유행 중인 질병",
        },
      ],
    },
    duration: { minTicks: 8, maxTicks: 20 },
    immediateEffects: [
      { targetMetric: "settlement.diseaseLevel", operation: "add", value: 0.4, minimum: 0, maximum: 1 },
    ],
    ongoingEffects: [
      { targetMetric: "settlement.stability", operation: "multiply", value: 0.92, minimum: 0, maximum: 100 },
    ],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 36,
    maximumConcurrentInstances: 1,
    importance: 75,
    tags: ["health"],
    source: "builtin",
  },
  {
    id: "foodRiot",
    version: 1,
    category: "social",
    kind: "effect",
    name: "식량 폭동",
    descriptionTemplate: "굶주린 {settlement} 주민들이 곳간을 향해 들고일어났다.",
    scope: "settlement",
    preconditions: [
      { metric: "settlement.foodMonthsRemaining", operator: "lt", value: 1.2 },
      { metric: "settlement.stability", operator: "lt", value: 55 },
    ],
    probability: {
      base: 0.02,
      factors: [
        {
          source: "foodRiot.famine",
          condition: { metric: "settlement.foodMonthsRemaining", operator: "lt", value: 0.5 },
          multiplier: 2.5,
          explanation: "재고 0.5개월 미만 — 극심한 부족",
        },
        {
          source: "foodRiot.unstable",
          condition: { metric: "settlement.stability", operator: "lt", value: 35 },
          multiplier: 1.8,
          explanation: "안정도 35 미만 — 통제력 상실",
        },
      ],
    },
    duration: { minTicks: 3, maxTicks: 8 },
    immediateEffects: [
      { targetMetric: "settlement.stability", operation: "add", value: -12, minimum: 0, maximum: 100 },
    ],
    ongoingEffects: [
      { targetMetric: "settlement.stability", operation: "multiply", value: 0.75, minimum: 0, maximum: 100 },
    ],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 12,
    maximumConcurrentInstances: 1,
    importance: 70,
    tags: ["social", "food"],
    source: "builtin",
  },
  {
    id: "massMigration",
    version: 1,
    category: "social",
    kind: "notification",
    name: "대규모 이주",
    descriptionTemplate: "{settlement} 인구의 상당수가 도시를 떠나고 있다.",
    scope: "settlement",
    preconditions: [
      { metric: "settlement.lastOutMigrationRatio", operator: "gte", value: 0.03 },
    ],
    // 통지형 — 확률 판정 없이 임계값(순유출 ≥ 5%)으로 발생한다 (§12.4)
    probability: { base: 1, factors: [] },
    duration: { minTicks: 0, maxTicks: 0 },
    immediateEffects: [],
    ongoingEffects: [],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 6,
    maximumConcurrentInstances: 1,
    importance: 65,
    tags: ["social", "migration"],
    source: "builtin",
  },
  {
    id: "routeDisruption",
    version: 1,
    category: "economic",
    kind: "effect",
    name: "교역로 단절",
    descriptionTemplate: "{target} 경로가 끊겨 물자가 오가지 못한다.",
    scope: "route",
    preconditions: [],
    probability: {
      base: 0.0012,
      factors: [],
    },
    duration: { minTicks: 6, maxTicks: 18 },
    immediateEffects: [],
    ongoingEffects: [{ targetMetric: "route.capacity", operation: "multiply", value: 0.05, minimum: 0 }],
    resolutionEffects: [],
    followUpCandidates: [],
    cooldownTicks: 24,
    maximumConcurrentInstances: 1,
    importance: 55,
    tags: ["economic", "trade"],
    source: "builtin",
  },
];
